In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df_books = pd.read_csv('Books.csv')
df_ratings = pd.read_csv('Ratings.csv')
df_users = pd.read_csv('Users.csv')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14824\1085258990.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_books = pd.read_csv('Books.csv')

In [3]:
df_books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
df_ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [5]:
df_users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
print ("Books : {}".format(df_books.shape))
print ("Ratings : {}".format(df_ratings.shape))
print ("Users : {}".format(df_users.shape))

Books : (271360, 8)
Ratings : (1149780, 3)
Users : (278858, 3)

In [7]:
print ("Books : {}".format(df_books.info()))
print ("Ratings : {}".format(df_ratings.info()))
print ("Users : {}".format(df_users.info()))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271359 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB
Books : None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB
Ratings : None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB
Users : None

In [8]:
print ("Books : {}".format(df_books.isnull().sum()))
print ("Ratings : {}".format(df_ratings.isnull().sum()))
print ("Users : {}".format(df_users.isnull().sum()))

Books : ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64
Ratings : User-ID        0
ISBN           0
Book-Rating    0
dtype: int64
Users : User-ID          0
Location         0
Age         110762
dtype: int64

In [9]:
print ("Books : {}".format(df_books.columns))
print ("Ratings : {}".format(df_ratings.columns))
print ("Users : {}".format(df_users.columns))

Books : Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')
Ratings : Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')
Users : Index(['User-ID', 'Location', 'Age'], dtype='object')

In [10]:
print ("Books : {}".format(df_books['ISBN'].nunique()))
print ("Ratings : {}".format(df_ratings['ISBN'].nunique()))

Books : 271360
Ratings : 340556

In [11]:
# Join ratings and books dataframes
df=pd.merge(df_ratings,df_books,on="ISBN")

# Shape of the data
df.shape

(1031136, 10)

In [12]:
# Take 1 % data as sample  
df_sample = df.sample(frac=.01, random_state=1) 

# Shape of the sample data
df_sample.shape

(10311, 10)

In [13]:
# Create Item-user matrix using pivot_table()
df_pivot = df_sample.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating').fillna(0)

# Show top-5 records
df_pivot.head()

User-ID,254,432,507,625,638,726,730,805,834,876,...,278314,278418,278554,278563,278582,278663,278771,278838,278843,278851
Book-Title,,,,,,,,,,,,,,,,,,,,,
Garfield Bigger and Better (Garfield (Numbered Paperback)),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Good Wives: Image and Reality in the Lives of Women in Northern New England, 1650-1750",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Little Comic Shop of Horrors (Give Yourself Goosebumps, Book 17)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Summonings: Books of Magic, Vol. 2",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
' Mein verwundetes Herz'. Das Leben der Lilli Jahn 1900 - 1944.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# Import NearestNeighbors
from sklearn.neighbors import NearestNeighbors

# Build NearestNeighbors Object
model_nn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=7, n_jobs=-1)

# Fit the NearestNeighbor
model_nn.fit(df_pivot)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=7)

In [28]:
# Get top 10 nearest neighbors 
indices=model_nn.kneighbors(df_pivot.loc[['Souls Belated (Penguin Classics 60s)']], 10, return_distance=False)

# Print the recommended books
print("Recommended Books:")
print("==================")
for index, value in enumerate(df_pivot.index[indices][0]):
    print((index+1),". ",value)

Recommended Books:
==================
1 .  Souls Belated (Penguin Classics 60s)
2 .  Soul Among Lions: The Cougar As Peaceful Adversary
3 .  Soul Survivor
4 .  Sophies Choice
5 .  Sorcerer's Son
6 .  Sorceress of Darshiva (Malloreon (Paperback Random House))
7 .  Sosa : An Autobiography
8 .  Soothing Soaps: For Healthy Skin
9 .  Soul Harvest: The World Takes Sides (Left Behind No. 4)
10 .  Sounds and Silences: Poetry for Now

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14824\2317618981.py:7: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  for index, value in enumerate(df_pivot.index[indices][0]):

In [29]:
df[df['Book-Title'] == "10 Secrets for Success and Inner Peace"]

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
433577,10951,1561708755,0,10 Secrets for Success and Inner Peace,Wayne W. Dyer,2002,Hay House,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...
433578,22351,1561708755,5,10 Secrets for Success and Inner Peace,Wayne W. Dyer,2002,Hay House,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...
433579,109574,1561708755,0,10 Secrets for Success and Inner Peace,Wayne W. Dyer,2002,Hay House,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...
433580,112898,1561708755,7,10 Secrets for Success and Inner Peace,Wayne W. Dyer,2002,Hay House,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...
433581,113519,1561708755,0,10 Secrets for Success and Inner Peace,Wayne W. Dyer,2002,Hay House,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...,http://images.amazon.com/images/P/1561708755.0...

In [30]:
df[df['Book-Title'] == "Sorcerer's Son"]

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
626888,26621,0345276426,0,Sorcerer's Son,Phyllis Eisenstein,1979,Not Avail,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...
626889,127233,0345276426,0,Sorcerer's Son,Phyllis Eisenstein,1979,Not Avail,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...
626890,196077,0345276426,0,Sorcerer's Son,Phyllis Eisenstein,1979,Not Avail,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...
626891,236757,0345276426,0,Sorcerer's Son,Phyllis Eisenstein,1979,Not Avail,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...
626892,248718,0345276426,10,Sorcerer's Son,Phyllis Eisenstein,1979,Not Avail,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...,http://images.amazon.com/images/P/0345276426.0...

In [31]:
df[df['User-ID'] == 254]

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1670,254,0451167317,8,The Dark Half,Stephen King,1994,Signet Book,http://images.amazon.com/images/P/0451167317.0...,http://images.amazon.com/images/P/0451167317.0...,http://images.amazon.com/images/P/0451167317.0...
1994,254,043935806X,0,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
9099,254,0804106304,0,The Joy Luck Club,Amy Tan,1994,Prentice Hall (K-12),http://images.amazon.com/images/P/0804106304.0...,http://images.amazon.com/images/P/0804106304.0...,http://images.amazon.com/images/P/0804106304.0...
12722,254,0439064864,9,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439064864.0...,http://images.amazon.com/images/P/0439064864.0...,http://images.amazon.com/images/P/0439064864.0...
32035,254,0553273604,0,Of Love and Shadows,Isabel Allende,1988,Bantam Books,http://images.amazon.com/images/P/0553273604.0...,http://images.amazon.com/images/P/0553273604.0...,http://images.amazon.com/images/P/0553273604.0...
...,...,...,...,...,...,...,...,...,...,...
197694,254,1573226882,0,Fever Pitch,Nick Hornby,1998,Riverhead Books,http://images.amazon.com/images/P/1573226882.0...,http://images.amazon.com/images/P/1573226882.0...,http://images.amazon.com/images/P/1573226882.0...
197717,254,1583140379,0,Fools Rush in (Arabesque),Gwynne Forster,1999,Bet Books,http://images.amazon.com/images/P/1583140379.0...,http://images.amazon.com/images/P/1583140379.0...,http://images.amazon.com/images/P/1583140379.0...
197720,254,1592571301,0,Alpha Teach Yourself American Sign Language in...,Trudy Suggs,2003,Alpha Books,http://images.amazon.com/images/P/1592571301.0...,http://images.amazon.com/images/P/1592571301.0...,http://images.amazon.com/images/P/1592571301.0...
197721,254,1861870019,0,"My Daughter, My Joy: The Greatest Tributes to ...",Helen Exley,1998,Exley Giftbooks,http://images.amazon.com/images/P/1861870019.0...,http://images.amazon.com/images/P/1861870019.0...,http://images.amazon.com/images/P/1861870019.0...
197722,254,1931081727,9,The Devil You Know,Poppy Z. Brite,2003,Subterranean Press,http://images.amazon.com/images/P/1931081727.0...,http://images.amazon.com/images/P/1931081727.0...,http://images.amazon.com/images/P/1931081727.0...